DROP TABLE car_sales;
CREATE TABLE car_sales( ID INTEGER NOT NULL AUTO_INCREMENT,
last_name VARCHAR(256), company VARCHAR(256), cost DOUBLE, model VARCHAR(256), PRIMARY KEY(ID));

insert into car_sales (last_name, company, cost, model) values ('Searight', 'Ford', '93066.97', 'Bronco');
insert into car_sales (last_name, company, cost, model) values ('Faulks', 'Volkswagen', '21682.10', 'Eos');
insert into car_sales (last_name, company, cost, model) values ('Rapin', 'Bentley', '92110.46', 'Azure');
insert into car_sales (last_name, company, cost, model) values ('Perrett', 'Land Rover', '31742.08', 'Discovery Series II');
insert into car_sales (last_name, company, cost, model) values ('Janikowski', 'Lamborghini', '92271.29', 'Diablo');
insert into car_sales (last_name, company, cost, model) values ('Rushford', 'Hyundai', '97227.45', 'Entourage');
insert into car_sales (last_name, company, cost, model) values ('Ianitti', 'Ford', '61913.10', 'Freestyle');
insert into car_sales (last_name, company, cost, model) values ('Rawsthorne', 'BMW', '99779.86', '8 Series');
insert into car_sales (last_name, company, cost, model) values ('Gerbel', 'Dodge', '42555.94', 'Ram Van 1500');
insert into car_sales (last_name, company, cost, model) values ('Bartley', 'Kia', '17228.82', 'Optima');
insert into car_sales (last_name, company, cost, model) values ('Jirka', 'Toyota', '47172.56', 'Echo');
insert into car_sales (last_name, company, cost, model) values ('Billin', 'Suzuki', '46947.53', 'SJ 410');
insert into car_sales (last_name, company, cost, model) values ('Sapsforde', 'Chevrolet', '65146.03', 'Beretta');
insert into car_sales (last_name, company, cost, model) values ('Dadswell', 'Chevrolet', '36762.06', 'Colorado');
insert into car_sales (last_name, company, cost, model) values ('Steet', 'Oldsmobile', '19720.01', 'Aurora');
insert into car_sales (last_name, company, cost, model) values ('Wrassell', 'Lincoln', '57876.26', 'Town Car');
insert into car_sales (last_name, company, cost, model) values ('Fairhall', 'Dodge', '65473.68', 'Daytona');
insert into car_sales (last_name, company, cost, model) values ('Shallcrass', 'Suzuki', '91873.70', 'SJ');
insert into car_sales (last_name, company, cost, model) values ('Symons', 'Volkswagen', '93876.91', 'Fox');
insert into car_sales (last_name, company, cost, model) values ('MacCarter', 'Toyota', '54112.36', 'RAV4');
insert into car_sales (last_name, company, cost, model) values ('Baline', 'BMW', '62221.14', 'X3');
insert into car_sales (last_name, company, cost, model) values ('Chaikovski', 'Jaguar', '98671.30', 'X-Type');
insert into car_sales (last_name, company, cost, model) values ('Elphick', 'Ford', '41056.09', 'Bronco II');
insert into car_sales (last_name, company, cost, model) values ('Woolaghan', 'Toyota', '89627.00', 'Solara');
insert into car_sales (last_name, company, cost, model) values ('Almon', 'Volkswagen', '30721.52', 'GTI');
insert into car_sales (last_name, company, cost, model) values ('Knutsen', 'Toyota', '99189.83', 'MR2');
insert into car_sales (last_name, company, cost, model) values ('Laban', 'Acura', '44211.00', 'Integra');
insert into car_sales (last_name, company, cost, model) values ('Steven', 'Volkswagen', '23857.66', 'GTI');
insert into car_sales (last_name, company, cost, model) values ('Wrathmall', 'Land Rover', '40356.59', 'Freelander');
insert into car_sales (last_name, company, cost, model) values ('Petchey', 'Ford', '32927.35', 'E-Series');
insert into car_sales (last_name, company, cost, model) values ('Titcombe', 'Bentley', '10825.54', 'Continental');
